version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Deploying to S3 bucket: $S3_BUCKET"
      - aws s3 sync build/ "s3://$S3_BUCKET"
      - echo "Invalidating CloudFront cache for Distribution ID: $DISTRIBUTION_ID"
      - aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION_ID" --paths "/*"

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
